### ISSUE TITLE
Package won't install, please would you update.

### ISSUE THREAD

**Issue by justfreesites** [thanhdv2811/Magento-2-Currency-Convert#2]
Attempting to install via composer and receive the following error:

[InvalidArgumentException]
  Could not find a version of package thanhdv2811/magento-2-currency-convert
  matching your minimum-stability (stable). Require it with an explicit versi
  on constraint allowing its desired stability.

Please would you update or explain how I can install it manually.

**Comment by thanhdv2811** [comment]
I fixed the composer issue. You can install using composer from now
